# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name dmdrDense
#' @title Distributed Mean Dimension Reduction with Dense Solutions
#' @description Performs distributed parameter estimation using data partitioned across multiple machines.
#' Iteratively updates parameters by computing local scores and Hessian matrices, combining them to refine estimates.
#'
#' @param data A numeric matrix where the last column is the response variable and preceding columns are predictors.
#' @param machines Integer specifying the number of machines for computation.
#' @param d Integer indicating the reduced dimension for parameter estimation.
#' @param maxIter Maximum number of iterations (default: 1000).
#' @param tol Convergence tolerance for parameter updates (default: 1e-6).
#'
#' @return A numeric matrix containing the final estimated reduced-rank coefficient matrix.
#'
#' @details
#' The data is partitioned across `machines`, and local computations are performed to estimate scores and Hessians.
#' These are aggregated to iteratively refine global parameter estimates. Bandwidths `h1`, `h2`, and `h3` are updated
#' dynamically based on the partition size `n` as \eqn{n^{-1 / (4 + d)}}. The algorithm converges when parameter changes
#' fall below `tol`. Singular value decomposition (SVD) is applied to the final matrix to ensure stability and interpretability.
#'
#' @export
dmdrDense <- function(data, machines, d, maxIter = 1000L, tol = 1e-6, useParallel = FALSE) {
    .Call('_DMDR_dmdrDense', PACKAGE = 'DMDR', data, machines, d, maxIter, tol, useParallel)
}

dmdrSparse <- function(data, machines, d, maxIter = 100L, tol = 1e-6, useParallel = FALSE) {
    .Call('_DMDR_dmdrSparse', PACKAGE = 'DMDR', data, machines, d, maxIter, tol, useParallel)
}

solveLasso <- function(H1, betaCoef, lambda = 0.1, maxIter = 1000L, tol = 1e-6) {
    .Call('_DMDR_solveLasso', PACKAGE = 'DMDR', H1, betaCoef, lambda, maxIter, tol)
}

#' @name epanKernel
#' @title Epanichnikov Kernel for One Dimension
#' @description Computes the Epanichnikov kernel value for a scalar input.
#' @param u A numeric value representing the input.
#' @return A numeric value representing the kernel evaluation.
#' @export
NULL

#' @name epanKernelMulti
#' @title Multivariate Epanichnikov Kernel
#' @description Computes the product of Epanichnikov kernel values for a multivariate input.
#' @param u A numeric row vector representing the input.
#' @return A numeric value representing the kernel evaluation.
#' @export
NULL

#' @name vecLower
#' @title Extract Lower Triangular Block of a Matrix
#' @description Extracts and vectorizes the lower triangular portion of a matrix.
#' @param m A numeric matrix input.
#' @param p Number of rows in the matrix.
#' @param d Number of columns in the triangular block.
#' @return A numeric vector representing the vectorized lower triangular block.
#' @export
NULL

#' @name vecInv
#' @title Inverse Operation of vecLower
#' @description Reconstructs a matrix from its vectorized lower triangular block.
#' @param v A numeric vector representing the lower triangular block.
#' @param p Number of rows in the reconstructed matrix.
#' @param d Number of columns in the triangular block.
#' @return A numeric matrix reconstructed from the input vector.
#' @export
NULL

#' @name estimateScore
#' @title Estimate Scores and Parameters
#' @description Implements the main algorithm for estimating scores and parameters.
#' @param X A numeric matrix (n x p) of predictors.
#' @param alpha A numeric matrix (p x d) of transformation coefficients.
#' @param Y A numeric vector (n) of responses.
#' @param weights A numeric vector (n) of observation weights.
#' @param h1 Bandwidth parameter for regression kernel.
#' @param h2 Bandwidth parameter for weight estimation kernel.
#' @param h3 Bandwidth parameter for covariate adjustment kernel.
#' @param isCentral A boolean indicating whether to compute centralized scores.
#' @return A list containing:
#'   - \code{mHat}: Vector of estimated intercepts.
#'   - \code{m1Hat}: Matrix of estimated slope coefficients.
#'   - \code{eWHat}: Vector of weighted averages of responses.
#'   - \code{exWHat}: Matrix of weighted averages of predictors.
#'   - \code{scoreHat}: Matrix of estimated scores.
#'   - \code{eScore}: Vector of mean scores.
#'   - \code{H}: Matrix of estimated Hessians.
#' @export
estimateScore <- function(X, alpha, Y, h1, h2, h3) {
    .Call('_DMDR_estimateScore', PACKAGE = 'DMDR', X, alpha, Y, h1, h2, h3)
}

estimateScoreSparse <- function(X, alpha, Y, h1, h2, h3) {
    .Call('_DMDR_estimateScoreSparse', PACKAGE = 'DMDR', X, alpha, Y, h1, h2, h3)
}

mave_fit <- function(X, Y, d, h = 1, max_iter = 100L, tol = 1e-6) {
    .Call('_DMDR_mave_fit', PACKAGE = 'DMDR', X, Y, d, h, max_iter, tol)
}

